Proje000/Controllers/TakimKayitController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Proje000.Data;

namespace Proje000.Controllers
{
    public class TakimKayitController : Controller
    {
        private readonly DataContext _context;
        public TakimKayitController(DataContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var takimK = await _context.takimkayits
                .Include(x => x.Personel)
                .Include(x => x.Takim)
                .Include (x => x.Vardiya)
                .Include(x => x.Yonetici)
                .ToListAsync();
            return View(takimK);
        }
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var personList = await _context.personels
                .Select(p => new SelectListItem
                {
                    Text = p.Adi, // veya diğer bir isim alanı
                    Value = p.Id.ToString() // veya diğer bir benzersiz kimlik alanı
                })
                .ToListAsync();

            var takimList = await _context.takims
                .Select(t => new SelectListItem
                {
                    Text = t.TakimAdi, 
                    Value = t.Id.ToString() 
                })
                .ToListAsync();
            var vardiyaList = await _context.vardiyas
                .Select(v => new SelectListItem
                {
                    Text = v.VardiyaName, // veya diğer bir isim alanı
                    Value = v.Id.ToString() // veya diğer bir benzersiz kimlik alanı
                })
                .ToListAsync();
            var yoneticiList = await _context.yoneticis
                .Select(v => new SelectListItem
                {
                    Text = v.Adi, // veya diğer bir isim alanı
                    Value = v.Id.ToString() // veya diğer bir benzersiz kimlik alanı
                })
                .ToListAsync();

            ViewBag.personels = new SelectList(personList, "Value", "Text");
            ViewBag.takims = new SelectList(takimList, "Value", "Text");
            ViewBag.vardiyas = new SelectList(vardiyaList, "Value", "Text");
            ViewBag.yoneticis = new SelectList(yoneticiList, "Value", "Text");



            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create (TakimKayit model)
        {
            _context.takimkayits.Add(model);   
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
        [HttpGet]
        public async Task<ActionResult> Edit(int? Id)
        {
            var personList = await _context.personels
               .Select(p => new SelectListItem
               {
                   Text = p.Adi, // veya diğer bir isim alanı
                   Value = p.Id.ToString() // veya diğer bir benzersiz kimlik alanı
               })
               .ToListAsync();

            var takimList = await _context.takims
                .Select(t => new SelectListItem
                {
                    Text = t.TakimAdi,
                    Value = t.Id.ToString()
                })
                .ToListAsync();
            var vardiyaList = await _context.vardiyas
                .Select(v => new SelectListItem
                {
                    Text = v.VardiyaName, // veya diğer bir isim alanı
                    Value = v.Id.ToString() // veya diğer bir benzersiz kimlik alanı
                })
                .ToListAsync();
            var yoneticiList = await _context.yoneticis
                .Select(v => new SelectListItem
                {
                    Text = v.Adi, // veya diğer bir isim alanı
                    Value = v.Id.ToString() // veya diğer bir benzersiz kimlik alanı
                })
                .ToListAsync();

            ViewBag.personels = new SelectList(personList, "Value", "Text");
            ViewBag.takims = new SelectList(takimList, "Value", "Text");
            ViewBag.vardiyas = new SelectList(vardiyaList, "Value", "Text");
            ViewBag.yoneticis = new SelectList(yoneticiList, "Value", "Text");



            //return View();
            return View();
        }
        [HttpPost]
        // [ValidateAntiForgeryToken] güvenlik önmeli başkasının senin yerine değişiklik ypamasını engeller kullanılabilir 
        public async Task<IActionResult> Edit(int id, TakimKayit model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {

                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (Exception)
                {
                    if (!_context.takimkayits.Any(p => p.Id == model.Id))
                    {
                        return BadRequest();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(model);
        }


        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var takimKayit = await _context.takimkayits.FindAsync(id);

            if (takimKayit == null)
            {
                return NotFound();
            }
            return View(takimKayit);
        }
        [HttpPost]
        public async Task<IActionResult> Delete([FromForm] int id)
        {
            var takimKayit = await _context.takimkayits.FindAsync(id);
            if (takimKayit == null)
            {
                return NotFound();
            }
            _context.takimkayits.Remove(takimKayit);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

    }
}
      

Proje000/Views/TakimKayit/Create.cshtml
@model TakimKayit

<h2> Takim Kayit Ekleme</h2>
<hr>
<form asp-controller="TakimKayit" asp-action="Create" method="post">
    <div class=" mb-3">
        <label  asp-for="PersonelId" class=" form-label">Personel</label>
        <select asp-for="PersonelId" asp-items="ViewBag.personels" class="form-control">
        <option value ="">Seçiniz</option>
        </select>
    </div>
    <div class=" mb-3">
        <label asp-for="TakimId" class=" form-label">Takım</label>
        <select asp-for="TakimId" asp-items="ViewBag.takims" class="form-control">
        <option value="">Seçiniz</option>
        </select>
    </div>
    <div class=" mb-3">
        <label asp-for="VardiyaId" class=" form-label">Vardiya</label>
        <select asp-for="VardiyaId" asp-items="ViewBag.vardiyas" class="form-control">
        <option value="">Seçiniz</option>
        </select>
    </div>
    <div class=" mb-3">
        <label asp-for="YoneticiId" class=" form-label">Yönetici</label>
        <select asp-for="YoneticiId" asp-items="ViewBag.yoneticis" class="form-control">
            <option value="">Seçiniz</option>
        </select>
    </div>
    <button type="submit" class="btn btn-secondary">Kaydet</button>
</form>

Proje000/Views/TakimKayit/Delete.cshtml
@model TakimKayit

<p>
    <b>  @Model.Id @Model.Id</b> Id li Takım Kaydını silmek istiyor musunuz?
    <form asp-action="Delete" method="post">
        <input type="hidden" value="@Model.Id" name="id">
        <button type="submit" class="btn btn-danger">Evet</button>
        <a asp-action="Index" class="btn-primary">Hayır</a>
    </form>
</p>

Proje000/Views/TakimKayit/Edit.cshtml
@model TakimKayit

<h2> Takim Kayit Düzenleme</h2>
<hr>
<form asp-controller="TakimKayit" asp-action="Edit" method="post">
    <div class=" mb-3">
        <label asp-for="PersonelId" class=" form-label">Personel</label>
        <select asp-for="PersonelId" asp-items="ViewBag.personels" class="form-control">
            <option value="">Seçiniz</option>
        </select>
    </div>
    <div class=" mb-3">
        <label asp-for="TakimId" class=" form-label">Takım</label>
        <select asp-for="TakimId" asp-items="ViewBag.takims" class="form-control">
            <option value="">Seçiniz</option>
        </select>
    </div>
    <div class=" mb-3">
        <label asp-for="VardiyaId" class=" form-label">Vardiya</label>
        <select asp-for="VardiyaId" asp-items="ViewBag.vardiyas" class="form-control">
            <option value="">Seçiniz</option>
        </select>
    </div>
    <div class=" mb-3">
        <label asp-for="YoneticiId" class=" form-label">Yönetici</label>
        <select asp-for="YoneticiId" asp-items="ViewBag.yoneticis" class="form-control">
            <option value="">Seçiniz</option>
        </select>
    </div>
    <button type="submit" class="btn btn-secondary">Kaydet</button>
</form>

Proje000/Views/TakimKayit/Index.cshtml
@model IEnumerable<TakimKayit>

    <h2> Kayıtlı Takımlar</h2>
<a href="/TakimKayit/Create" class=" btn btn-primary">Takım Kayıt</a>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th style="width: 150px;">@Html.DisplayNameFor(m => m.Id)</th>
                <th>@Html.DisplayNameFor(m => m.Personel.Adi)</th>
            <th>@Html.DisplayNameFor(m => m.Takim.TakimAdi)</th>
            <th>@Html.DisplayNameFor(m => m.Yonetici.Adi)</th>
            <th style=" width: 150px;">   </th>
            </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem =>item.Id) </td>
                <td>@Html.DisplayFor(modelItem => item.Personel.Adi) </td>
                <td>@Html.DisplayFor(modelItem => item.Takim.TakimAdi) </td>
                <td>@Html.DisplayFor(modelItem => item.Yonetici.Adi) </td>
                <td>
                    <a  asp-controller="TakimKayit" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-primary">Düzenleme</a>
                    <a  asp-controller="TakimKayit" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">Sil</a>
                </td>
            </tr>
        }
        </tbody>
    </table>