Proje000/Controllers/PersonelController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Proje000.Data;

namespace Proje000.Controllers
{
public class PersonelController : Controller
    {
    private readonly DataContext _context;
    public PersonelController(DataContext context)
        {
         _context = context;
        }

        public async Task<IActionResult> Index()
        {

            return View(await _context.personels.ToListAsync());
        }
    public IActionResult Create()
        {
        return View();
        }
    [HttpPost]
    public async Task <IActionResult> Create(Personel model) 
        { 
         _context.personels.Add(model); 
          await  _context.SaveChangesAsync();

        return RedirectToAction("Index");
        }
        public async Task<ActionResult>Edit(int? Id)
        {
            if(Id == null)
            {
                return NotFound();
            }
            var prs = await _context.personels.FindAsync(Id);
            if (prs == null)
            {
                return NotFound();

            }
            return View(prs);
        }
        [HttpPost]
        // [ValidateAntiForgeryToken] güvenlik önmeli başkasının senin yerine değişiklik ypamasını engeller kullanılabilir 
        public async Task<IActionResult> Edit(int id, Personel model)
        {
            if(id != model.Id)
            {
                return NotFound();
            }
            if(ModelState.IsValid)
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (Exception)
                {
                    if (!_context.personels.Any(p => p.Id == model.Id))
                    {
                        return BadRequest();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }   
            return View(model);
        }


        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var personel = await _context.personels.FindAsync(id);

            if(personel == null)
            {
                return NotFound();
            }
            return View(personel);
        }
        [HttpPost]
        public async Task<IActionResult> Delete([FromForm]int id)
        {
            var personel = await _context.personels.FindAsync(id);
            if (personel == null)
            {
                return NotFound();
            }
            _context.personels.Remove(personel);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
            


    }
}

Proje000/Controllers/TakimController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Proje000.Data;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Proje000.Controllers
{
    public class TakimController : Controller
    {
        private readonly DataContext _context;

        public TakimController(DataContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var takims = await _context.takims.ToListAsync();
            return View(takims);
        }

        public async Task<IActionResult> Create()
        {
           
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Takim model)
        {
            

                _context.takims.Add(model);
                await _context.SaveChangesAsync();

                return RedirectToAction("Index");
          

        
        }

        public async Task<ActionResult> Edit(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            var tkm = await _context.takims.FindAsync(Id);
            if (tkm == null)
            {
                return NotFound();

            }
            return View(tkm);
        }
        [HttpPost]
        
        public async Task<IActionResult> Edit(int id, Takim model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (Exception)
                {
                    if (!_context.takims.Any(t => t.Id == model.Id))
                    {
                        return BadRequest();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

Proje000/Controllers/VardiyaController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Proje000.Data;

namespace Proje000.Controllers
{
    public class VardiyaController : Controller
    {
        private readonly DataContext _context;
        public VardiyaController(DataContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var vardiya = await _context.vardiyas.ToListAsync();
            return View(vardiya);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Vardiya model)
        {
            _context.vardiyas.Add(model);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
        public async Task<ActionResult> Edit(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            var tkm = await _context.vardiyas.FindAsync(Id);
            if (tkm == null)
            {
                return NotFound();

            }
            return View(tkm);
        }
        [HttpPost]
        // [ValidateAntiForgeryToken] güvenlik önmeli başkasının senin yerine değişiklik ypamasını engeller kullanılabilir 
        public async Task<IActionResult> Edit(int id, Vardiya model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (Exception)
                {
                    if (!_context.vardiyas.Any(t => t.Id == model.Id))
                    {
                        return BadRequest();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var vardiya = await _context.vardiyas.FindAsync(id);

            if (vardiya == null)
            {
                return NotFound();
            }
            return View(vardiya);
        }
        [HttpPost]
        public async Task<IActionResult> Delete([FromForm] int id)
        {
            var vardiya = await _context.vardiyas.FindAsync(id);
            if (vardiya == null)
            {
                return NotFound();
            }
            _context.vardiyas.Remove(vardiya);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }



    }
}
    

Proje000/Controllers/YoneticiController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Proje000.Data;

namespace Proje000.Controllers
{
    public class YoneticiController : Controller
    {
        private readonly DataContext _context;
        public YoneticiController(DataContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {

            return View(await _context.yoneticis.ToListAsync());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(Yonetici model)
        {
            _context.yoneticis.Add(model);
            await _context.SaveChangesAsync();

            return RedirectToAction("Index");
        }
        public async Task<ActionResult> Edit(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }
            var ynt = await _context.yoneticis.FindAsync(Id);
            if (ynt == null)
            {
                return NotFound();

            }
            return View(ynt);
        }
        [HttpPost]
        // [ValidateAntiForgeryToken] güvenlik önmeli başkasının senin yerine değişiklik ypamasını engeller kullanılabilir 
        public async Task<IActionResult> Edit(int id, Yonetici model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(model);
                    await _context.SaveChangesAsync();
                }
                catch (Exception)
                {
                    if (!_context.yoneticis.Any(p => p.Id == model.Id))
                    {
                        return BadRequest();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(model);
        }


        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var yonetici = await _context.yoneticis.FindAsync(id);

            if (yonetici == null)
            {
                return NotFound();
            }
            return View(yonetici);
        }
        [HttpPost]
        public async Task<IActionResult> Delete([FromForm] int id)
        {
            var yonetici = await _context.yoneticis.FindAsync(id);
            if (yonetici == null)
            {
                return NotFound();
            }
            _context.yoneticis.Remove(yonetici);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }



    }
}

Proje000/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Proje000</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Proje000.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Proje000</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Personel"
                            asp-action="Index">Personel</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Takim"
                               asp-action="Index">Takımlar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Yonetici"
                               asp-action="Index">Yönetici</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vardiya"
                               asp-action="Index">Vardiya</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TakimKayit"
                               asp-action="Index">Takım Kayıtları</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Proje000 - <a asp-area="" asp-controller="Personel" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>